// Fake employee data with full onboarding details

export const employeesData = [
  {
    id: "6a3001",
    employee_id: "EMP001",
    first_name: "Rahul",
    last_name: "Verma",
    official_email: "rahul.v@company.com",
    phone: "+919876543210",
    department: "Engineering",
    designation: "Senior Developer",
    reporting_manager: "Vikram Singh",
    joining_date: "2022-01-10",
    employment_type: "full-time",
    shift: "General (9AM-6PM)",
    work_location: "Hyderabad Office",
    status: "active",
    onboarding_progress: 100,
    salary_structure: { basic: 90000, hra: 36000, special_allowance: 24000, ctc: 1800000 },
    personal_details: { date_of_birth: "1996-05-12", gender: "male", blood_group: "O+", marital_status: "single" },
    address: { current: { line1: "Flat 302, Sapphire Towers", city: "Hyderabad", state: "Telangana", pincode: "500081" }, permanent: { line1: "H.No 45, MG Road", city: "Vizag", state: "Andhra Pradesh", pincode: "530001" } },
    emergency_contact: { name: "Suresh Verma", relation: "Father", phone: "+919876500001" },
    bank_details: { account_number: "XXXX4521", ifsc: "SBIN0001234", bank_name: "State Bank of India" },
    government_ids: { pan: { number: "ABCDE1234F", document_url: "pan_rahul.pdf" }, aadhaar: { number: "XXXX-XXXX-4567", document_url: "aadhaar_rahul.pdf" } },
    education: [{ degree: "B.Tech Computer Science", university: "JNTU Hyderabad", year: 2018, document_url: "degree_rahul.pdf" }],
    experience: [{ company: "Infosys", role: "Software Engineer", from: "2018-07", to: "2021-12", document_url: "exp_infosys.pdf" }],
    documents: [{ name: "Passport Photo", url: "photo_rahul.jpg" }, { name: "Offer Letter Signed", url: "offer_rahul.pdf" }],
    policy_acceptance: { accepted: true, accepted_at: "2022-01-10" },
    onboarding_sections: { personal_details: { status: "completed", verified: true }, address: { status: "completed", verified: true }, emergency_contact: { status: "completed", verified: true }, bank_details: { status: "completed", verified: true }, government_ids: { status: "completed", verified: true }, education: { status: "completed", verified: true }, experience: { status: "completed", verified: true }, documents: { status: "completed", verified: true }, policy_acceptance: { status: "completed", verified: true } },
    created_at: "2022-01-05",
  },
  {
    id: "6a3002",
    employee_id: "EMP002",
    first_name: "Ananya",
    last_name: "Patel",
    official_email: "ananya.p@company.com",
    phone: "+919876543211",
    department: "Design",
    designation: "UI/UX Lead",
    reporting_manager: "Pooja Deshmukh",
    joining_date: "2021-06-20",
    employment_type: "full-time",
    shift: "Flexible (Core 11AM-4PM)",
    work_location: "Hyderabad Office",
    status: "active",
    onboarding_progress: 100,
    salary_structure: { basic: 80000, hra: 32000, special_allowance: 21000, ctc: 1600000 },
    personal_details: { date_of_birth: "1994-09-22", gender: "female", blood_group: "A+", marital_status: "married" },
    address: { current: { line1: "Villa 12, Jubilee Hills", city: "Hyderabad", state: "Telangana", pincode: "500033" }, permanent: { line1: "Villa 12, Jubilee Hills", city: "Hyderabad", state: "Telangana", pincode: "500033" } },
    emergency_contact: { name: "Rohan Patel", relation: "Husband", phone: "+919876500002" },
    bank_details: { account_number: "XXXX8923", ifsc: "HDFC0004567", bank_name: "HDFC Bank" },
    government_ids: { pan: { number: "FGHIJ5678K", document_url: "pan_ananya.pdf" }, aadhaar: { number: "XXXX-XXXX-8901", document_url: "aadhaar_ananya.pdf" } },
    education: [{ degree: "M.Des Interaction Design", university: "IIT Bombay", year: 2016, document_url: "degree_ananya.pdf" }],
    experience: [{ company: "Flipkart", role: "Senior Designer", from: "2016-08", to: "2021-05", document_url: "exp_flipkart.pdf" }],
    documents: [{ name: "Passport Photo", url: "photo_ananya.jpg" }],
    policy_acceptance: { accepted: true, accepted_at: "2021-06-20" },
    onboarding_sections: { personal_details: { status: "completed", verified: true }, address: { status: "completed", verified: true }, emergency_contact: { status: "completed", verified: true }, bank_details: { status: "completed", verified: true }, government_ids: { status: "completed", verified: true }, education: { status: "completed", verified: true }, experience: { status: "completed", verified: true }, documents: { status: "completed", verified: true }, policy_acceptance: { status: "completed", verified: true } },
    created_at: "2021-06-15",
  },
  {
    id: "6a3003",
    employee_id: "EMP003",
    first_name: "Karthik",
    last_name: "Rajan",
    official_email: "karthik.r@company.com",
    phone: "+919876543212",
    department: "Engineering",
    designation: "Junior Developer",
    reporting_manager: "Rahul Verma",
    joining_date: "2025-06-15",
    employment_type: "full-time",
    shift: "General (9AM-6PM)",
    work_location: "Hyderabad Office",
    status: "onboarding_in_progress",
    onboarding_progress: 67,
    salary_structure: { basic: 35000, hra: 14000, special_allowance: 9000, ctc: 700000 },
    personal_details: { date_of_birth: "2000-11-03", gender: "male", blood_group: "B+", marital_status: "single" },
    address: { current: { line1: "Room 4, PG Accommodation", city: "Hyderabad", state: "Telangana", pincode: "500072" }, permanent: { line1: "22, Gandhi Nagar", city: "Chennai", state: "Tamil Nadu", pincode: "600020" } },
    emergency_contact: { name: "Rajan K", relation: "Father", phone: "+919876500003" },
    bank_details: { account_number: "XXXX1122", ifsc: "ICIC0003456", bank_name: "ICICI Bank" },
    government_ids: { pan: { number: null, document_url: null }, aadhaar: { number: null, document_url: null } },
    education: [{ degree: "B.Tech IT", university: "Anna University", year: 2022, document_url: "degree_karthik.pdf" }],
    experience: [],
    documents: [],
    policy_acceptance: { accepted: true, accepted_at: "2025-06-16" },
    onboarding_sections: { personal_details: { status: "completed", verified: true }, address: { status: "completed", verified: true }, emergency_contact: { status: "completed", verified: false }, bank_details: { status: "completed", verified: false }, government_ids: { status: "pending", verified: false }, education: { status: "completed", verified: true }, experience: { status: "pending", verified: false }, documents: { status: "pending", verified: false }, policy_acceptance: { status: "completed", verified: true } },
    created_at: "2025-06-10",
  },
  {
    id: "6a3004",
    employee_id: "EMP004",
    first_name: "Sneha",
    last_name: "Reddy",
    official_email: "sneha.r@company.com",
    phone: "+919876543213",
    department: "Marketing",
    designation: "Marketing Manager",
    reporting_manager: "Pooja Deshmukh",
    joining_date: "2022-04-15",
    employment_type: "full-time",
    shift: "General (9AM-6PM)",
    work_location: "Bangalore Office",
    status: "active",
    onboarding_progress: 100,
    salary_structure: { basic: 70000, hra: 28000, special_allowance: 18000, ctc: 1400000 },
    personal_details: { date_of_birth: "1995-02-28", gender: "female", blood_group: "AB-", marital_status: "single" },
    address: { current: { line1: "Apt 5B, Whitefield", city: "Bangalore", state: "Karnataka", pincode: "560066" }, permanent: { line1: "Plot 7, Banjara Hills", city: "Hyderabad", state: "Telangana", pincode: "500034" } },
    emergency_contact: { name: "Priya Reddy", relation: "Mother", phone: "+919876500004" },
    bank_details: { account_number: "XXXX7788", ifsc: "AXIS0005678", bank_name: "Axis Bank" },
    government_ids: { pan: { number: "KLMNO9012P", document_url: "pan_sneha.pdf" }, aadhaar: { number: "XXXX-XXXX-3456", document_url: "aadhaar_sneha.pdf" } },
    education: [{ degree: "MBA Marketing", university: "ISB Hyderabad", year: 2019, document_url: "degree_sneha.pdf" }],
    experience: [{ company: "Zomato", role: "Marketing Lead", from: "2019-06", to: "2022-03", document_url: "exp_zomato.pdf" }],
    documents: [{ name: "Passport Photo", url: "photo_sneha.jpg" }],
    policy_acceptance: { accepted: true, accepted_at: "2022-04-15" },
    onboarding_sections: { personal_details: { status: "completed", verified: true }, address: { status: "completed", verified: true }, emergency_contact: { status: "completed", verified: true }, bank_details: { status: "completed", verified: true }, government_ids: { status: "completed", verified: true }, education: { status: "completed", verified: true }, experience: { status: "completed", verified: true }, documents: { status: "completed", verified: true }, policy_acceptance: { status: "completed", verified: true } },
    created_at: "2022-04-10",
  },
  {
    id: "6a3005",
    employee_id: "EMP005",
    first_name: "Meera",
    last_name: "Iyer",
    official_email: "meera.i@company.com",
    phone: "+919876543214",
    department: "HR",
    designation: "HR Executive",
    reporting_manager: "Priya Sharma",
    joining_date: "2025-06-20",
    employment_type: "full-time",
    shift: "General (9AM-6PM)",
    work_location: "Hyderabad Office",
    status: "pending_onboarding",
    onboarding_progress: 0,
    salary_structure: { basic: 40000, hra: 16000, special_allowance: 10000, ctc: 800000 },
    personal_details: null,
    address: null,
    emergency_contact: null,
    bank_details: null,
    government_ids: null,
    education: null,
    experience: null,
    documents: null,
    policy_acceptance: null,
    onboarding_sections: { personal_details: { status: "pending", verified: false }, address: { status: "pending", verified: false }, emergency_contact: { status: "pending", verified: false }, bank_details: { status: "pending", verified: false }, government_ids: { status: "pending", verified: false }, education: { status: "pending", verified: false }, experience: { status: "pending", verified: false }, documents: { status: "pending", verified: false }, policy_acceptance: { status: "pending", verified: false } },
    created_at: "2025-06-18",
  },
];
